image: johnjz/comp2300-platformio:ststm32-4.0.1

part-1:build_check:
  tags:
    - comp2300
  script:
    - git checkout origin/part-1
    - mv /comp2300-2018-assignment-1/.pioenvs .
    - pio run --disable-auto-clean

part-2:build_check:
  tags:
    - comp2300
  script:
    - git checkout origin/part-2
    - mv /comp2300-2018-assignment-1/.pioenvs .
    - pio run --disable-auto-clean

part-1:originality:
  tags:
    - comp2300
  script:
    - git checkout origin/part-1
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp2300/assets/schemas/statement-of-originality.json ./statement-of-originality.yml

part-2:originality:
  tags:
    - comp2300
  script:
    - git checkout origin/part-2
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp2300/assets/schemas/statement-of-originality.json ./statement-of-originality.yml

part-2:design_doc:
  tags:
    - comp2300
  script:
    - git checkout origin/part-2
    - python3 /validate.py --exists design-document.pdf
    